# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "site"

# This page should be the root of your website. It's important.
page = "https://fajrulfx.notion.site/fajrulfx/Fajrul-s-Blog-94f06de440a243b595b70b3d1c67cacc"

theme = "dark"
extension_in_links = false

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "title"
  content = "Fajrul Fx's Blog"
  [[site.meta]]
  name = "description"
  content = "Personal website of Fajrul Falah"

  [[site.inject.head.link]]
  rel="icon"
  sizes="16x16"
  type="image/png"
  href="favicon.png"
